#!/usr/bin/env python
# See https://github.com/SmartFinn/unetlab-x-integration/

from __future__ import print_function
from subprocess import Popen, PIPE

import sys


def main(argv):
    try:
        from urllib.parse import urlparse
    except ImportError:
        from urlparse import urlparse

    url = urlparse(argv)

    data = {
        'host': url.hostname,
        'port': url.port,
        'path': url.path.lstrip('/'),
    }

    if url.scheme == 'capture':
        cmd = 'ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no \
              -l root {host} tcpdump -i {path} -n -s 0 -U -w -'.format(**data)
        wireshark_cmd = 'wireshark -k -i -'

        tcpdump = Popen(cmd.split(), stdout=PIPE)
        wireshark = Popen(wireshark_cmd.split(), stdin=tcpdump.stdout)
        wireshark.communicate()
    elif url.scheme == 'docker':
        cmd = 'x-terminal-emulator -e \
              docker -H {host}:{port} attach {path}'.format(**data)

        Popen(cmd.split())
    elif url.scheme == 'telnet':
        cmd = 'x-terminal-emulator -e telnet {host} {port}'.format(**data)

        Popen(cmd.split())
    else:
        return 'URL "{}" is currently not supported.'.format(url.geturl())


if __name__ == '__main__':
    try:
        sys.exit(main(sys.argv[1]))
    except IndexError:
        print('usage:', __file__, '<url>', file=sys.stderr)
        sys.exit(1)
