#!/usr/bin/env python
# See https://github.com/SmartFinn/unetlab-x-integration/

from __future__ import print_function
from subprocess import Popen, PIPE

import sys


def main(argv):
    try:
        from urllib.parse import urlparse
    except ImportError:
        from urlparse import urlparse

    u = urlparse(argv)

    d = {
        'host': u.hostname,
        'port': u.port,
        'path': u.path.lstrip('/'),
    }

    if u.scheme == 'capture':
        cmd = 'ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no \
              -l root {host} tcpdump -i {path} -n -s 0 -U -w -'.format(**d)

        ssh_tcpdump = Popen(cmd.split(), stdout=PIPE)
        wireshark = Popen(['wireshark', '-k', '-i-'], stdin=ssh_tcpdump.stdout)
        wireshark.communicate()
    elif u.scheme == 'docker':
        cmd = 'x-terminal-emulator -e \
              docker -H {host}:{port} attach {path}'.format(**d)

        Popen(cmd.split())
    elif u.scheme == 'telnet':
        cmd = 'x-terminal-emulator -e telnet {host} {port}'.format(**d)

        Popen(cmd.split())
    else:
        return 'URL "{}" is currently not supported.'.format(u.geturl())


if __name__ == '__main__':
    try:
        sys.exit(main(sys.argv[1]))
    except IndexError:
        print('usage:', __file__, '<url>', file=sys.stderr)
        sys.exit(1)
