#!/usr/bin/env python
# See https://github.com/SmartFinn/unetlab-x-integration/

from __future__ import print_function
from subprocess import Popen

import sys


def main(argv):
    try:
        from urllib.parse import urlparse
    except ImportError:
        from urlparse import urlparse

    u = urlparse(argv)

    d = {
        'host': u.hostname,
        'port': u.port,
        'path': u.path.lstrip('/'),
    }

    if u.scheme == 'capture':
        Popen('ssh -l root {host} tcpdump -s 0 -U -n -i {path} -w - | \
            wireshark -k -i -'.format(**d), shell=True)
    elif u.scheme == 'docker':
        Popen('x-terminal-emulator -e \
            "docker -H {host}:{port} attach {path}"'.format(**d), shell=True)
    elif u.scheme == 'telnet':
        Popen('x-terminal-emulator -e "telnet {host} {port}"'.format(**d),
              shell=True)
    else:
        return 'URL "{}" is currently not supported.'.format(u.geturl())


if __name__ == '__main__':
    try:
        sys.exit(main(sys.argv[1]))
    except IndexError:
        print('usage:', __file__, '<url>', file=sys.stderr)
        sys.exit(1)
